# -*- coding: utf-8 -*-
"""Wildfire monitoring - Australia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hB5Z3KUaPkczjqPKi8YfZKKxx_tJJ3Ut
"""

!pip install -q xee geemap

import ee
import geemap as gee
import xarray as xr
import matplotlib.pyplot as plt
import shapely
import xee

from xee import helpers

ee.Authenticate()

ee.Initialize(
    project='ee-lavibas23',
    opt_url='https://earthengine-highvolume.googleapis.com'
)

Map = gee.Map(basemap='SATELLITE')
Map

roi = ee.Geometry.Rectangle([
    146.0, -38.8,   # xmin, ymin
    149.0, -36.8    # xmax, ymax
])

Map.centerObject(roi, 7)
Map.addLayer(roi, {'color': 'red'}, 'ROI')

Map

vec = shapely.geometry.shape(
    roi.getInfo()
)

time_start = ee.Date('2019-12-15')
time_end = ee.Date('2020-01-20')

sr = (
    ee.ImageCollection("NASA/VIIRS/002/VNP09GA")
    .filterDate(time_start, time_end)
    .filterBounds(roi)
    .select(['I1', 'I2'])
)

def ndvi(img):

    index = img.normalizedDifference(
        ['I2', 'I1']
    ).rename('ndvi')

    return index.copyProperties(
        img,
        img.propertyNames()
    )

viirs_ndvi = sr.map(ndvi)

grid_params_ndvi = helpers.fit_geometry(
    geometry=vec,
    grid_crs='EPSG:4326',
    grid_scale=(0.005, -0.005)
)

ds_ndvi = xr.open_dataset(
    viirs_ndvi,
    engine='ee',
    **grid_params_ndvi
)

print(ds_ndvi)

ds_ndvi.ndvi.plot(
    x='x',
    y='y',
    col='time',
    col_wrap=5,
    robust=True,
    cmap='YlGn'
)

plt.suptitle(
    'VIIRS NDVI over East Gippsland, Australia',
    fontsize=14
)

plt.savefig(
    'australia_ndvi_fire.png',
    dpi=360,
    bbox_inches='tight'
)


plt.show()

temp = (
    ee.ImageCollection("NASA/VIIRS/002/VNP14A1")
    .select('MaxFRP')
    .filterDate(time_start, time_end)
    .filterBounds(roi)
)

grid_params_temp = helpers.fit_geometry(
    geometry=vec,
    grid_crs='EPSG:4326',
    grid_scale=(0.01, -0.01)
)

ds_temp = xr.open_dataset(
    temp,
    engine='ee',
    **grid_params_temp
)

print(ds_temp)

print(temp.size().getInfo())

frp_test = temp.max()

print(
    frp_test.reduceRegion(
        reducer=ee.Reducer.max(),
        geometry=roi,
        scale=1000,
        maxPixels=1e9
    ).getInfo()
)

frp_max = temp.max()

ds_temp = xr.open_dataset(
    frp_max,
    engine='ee',
    **grid_params_temp
)

# Convert to numeric
ds_temp = ds_temp * 1

# Plot
ds_temp.MaxFRP.plot(
    x='x',
    y='y',
    cmap='hot',
    robust=True
)

plt.title(
    'Maximum Fire Radiative Power (FRP)'
)

plt.show()

ds_temp.MaxFRP.plot(
    x='x',
    y='y',
    col='time',
    col_wrap=5,
    robust=True,
    cmap='Reds'
)

plt.suptitle(
    'VIIRS Fire Radiative Power (FRP)',
    fontsize=14
)

plt.show()

lst = (
    ee.ImageCollection("NASA/VIIRS/002/VNP21A1D")
    .select('LST_1KM')
    .filterDate(time_start, time_end)
    .filterBounds(roi)
)

grid_params_lst = helpers.fit_geometry(
    geometry=vec,
    grid_crs='EPSG:4326',
    grid_scale=(0.01, -0.01)
)

ds_lst = xr.open_dataset(
    lst,
    engine='ee',
    **grid_params_lst
)

# Convert to Celsius
ds_lst['LST_1KM'] = (
    ds_lst['LST_1KM'] * 0.02
) - 273.15

print(ds_lst)

ds_lst.LST_1KM.plot(
    x='x',
    y='y',
    cmap='hot_r',
    col='time',
    col_wrap=5,
    robust=True
)

plt.suptitle(
    'VIIRS Land Surface Temperature (°C)',
    fontsize=14
)

plt.show()